apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
spec:
  maxReplicas: {{ .Values.swimlane.autoscaling.maxReps }}
  minReplicas: {{ .Values.swimlane.autoscaling.minReps }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.swimlane.autoscaling.cpuTarget }}